### ISSUE TITLE
Error in retrieving local authorization token

### ISSUE THREAD

**Issue by sandro-berchier** [leikoilja/glocaltokens#2]
Hi leikoilja -

first of all - thanks a lot for putting this together!

I'm able to retrieve Master and Access token.
Unfortunately I have struggled with retrieving the local authorization key.

Do you understand the error below? 
If so how can I fix?

Really appreciate your help!

Best,
Sandro

```python
[*] Google devices local authentication tokens
Traceback (most recent call last):
  File "/Users/sandro-berchier/Documents/SmartHome/test.py", line 17, in <module>
    google_devices = client.get_google_devices_json()
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/glocaltokens/client.py", line 126, in get_google_devices_json
    homegraph = self.get_homegraph()
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/glocaltokens/client.py", line 117, in get_homegraph
    response = rpc_service.GetHomeGraph(request)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/grpc/_channel.py", line 923, in __call__
    return _end_unary_response_blocking(state, call, False, None)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/grpc/_channel.py", line 826, in _end_unary_response_blocking
    raise _InactiveRpcError(state)
grpc._channel._InactiveRpcError: <_InactiveRpcError of RPC that terminated with:
        status = StatusCode.INTERNAL
        details = "Exception deserializing response!"
        debug_error_string = "None"
>
```

**Comment by leikoilja** [comment]
Hey, @sandro-berchier. Thanks for opening the issue, I was able to replicate the error just now and it seems the problem is with protobuf(https://github.com/grpc/grpc/issues/14847). I will take a closer look at this soon and get back to you

**Comment by sandro-berchier** [comment]
Hi @leikoilja  - it worked - thank you very much! Super helpful!

Have a great weekend :)
