### ISSUE TITLE
Can't connect to Google home addon - Could not get master token

### ISSUE THREAD

**Issue by ArnyminerZ** [leikoilja/glocaltokens#245]
Hello,

I have read the other issues with the same error than mine, but I couldn't resolve it.

I use the Google Home addon of Home Assistant, but the connection is refused.
I've tried to take off the protection methods to my google account too.

Here the log :
```
2022-05-13 10:58:25 DEBUG (MainThread) [glocaltokens.client] Initializing new GLocalAuthenticationTokens instance.
2022-05-13 10:58:25 DEBUG (MainThread) [glocaltokens.client] Set GLocalAuthenticationTokens client access_token, homegraph, access_token_date and homegraph_date to None
2022-05-13 10:58:25 DEBUG (MainThread) [glocaltokens.client] Set GLocalAuthenticationTokens client username to "m*******************", password to "V********", master_token to "" and android_id to
2022-05-13 10:58:25 DEBUG (SyncWorker_15) [glocaltokens.client] There is no stored master_token, logging in using username and password
2022-05-13 10:58:25 DEBUG (SyncWorker_15) [glocaltokens.client] There is no stored android_id, generating a new one
2022-05-13 10:58:25 DEBUG (SyncWorker_15) [glocaltokens.client] Generating android id...
2022-05-13 10:58:25 DEBUG (SyncWorker_15) [glocaltokens.client] Generated android id: 02d89392d5f67400
2022-05-13 10:58:25 ERROR (SyncWorker_15) [glocaltokens.client] [!] Could not get master token.
2022-05-13 10:58:25 DEBUG (SyncWorker_15) [glocaltokens.client] Request response: {'Error': 'NeedsBrowser', 'Url': 'https://accounts.google.com/signin/continue?sarp=1&scc=1&continue=https://accounts.google.com/o/android/IDELETEDTHIS', 'ErrorDetail': 'To access your account, you must sign in on the web. Touch Next to start browser sign-in.'} 2022-05-13 10:58:25 ERROR (MainThread) [custom_components.google_home]
```

**Edit**: Of course, no pop-up opens.

**Comment by ArnyminerZ** [comment]
Test performed with the example code, to check at basis if `glocaltokens` is still working. However, I'm getting the following error:
```
Traceback (most recent call last):
  File "get_tokens.py", line 6, in <module>
    from glocaltokens.client import GLocalAuthenticationTokens
  File "/home/arnyminerz/.local/lib/python3.8/site-packages/glocaltokens/client.py", line 24, in <module>
    from .google.internal.home.foyer.v1_pb2 import GetHomeGraphRequest, GetHomeGraphResponse
  File "/home/arnyminerz/.local/lib/python3.8/site-packages/glocaltokens/google/internal/home/foyer/v1_pb2.py", line 6, in <module>
    from google.protobuf import (
ModuleNotFoundError: No module named 'google'
```
Any ideas @leikoilja 🤔

**Comment by casper255** [comment]
It's the same for me


Logger: custom_components.google_home
Source: custom_components/google_home/config_flow.py:99
Integration: google_home (documentation, issues)
First occurred: 21:05:56 (1 occurrences)
Last logged: 21:05:56



Logger: glocaltokens.client
Source: /usr/local/lib/python3.9/site-packages/glocaltokens/client.py:224
First occurred: 21:05:56 (1 occurrences)
Last logged: 21:05:56

[!] Could not get master token.

**Comment by bjarnekrottje** [comment]
Same error for me.

UI Setup error:
![image](https://user-images.githubusercontent.com/46538710/170373282-8c417848-fbf6-41f1-b676-763c56d06f2f.png)

Logs:
![image](https://user-images.githubusercontent.com/46538710/170373405-3fd7a2f4-eaff-4029-a297-30fcedfc34ad.png)
![image](https://user-images.githubusercontent.com/46538710/170373432-88ac1ac4-1575-43e9-99f4-44744446cc6a.png)

Is there a (temporary) fix for this issue?

**Comment by tfrubio** [comment]
Same issue. If context helps, fresh/first install of HA/Google home addon today. Have ensured 2FA, SSL via Nabu Casa, using app password,  and unlocked captcha

```2022-05-25 20:50:56 DEBUG (MainThread) [glocaltokens.client] Initializing new GLocalAuthenticationTokens instance.
2022-05-25 20:50:56 DEBUG (MainThread) [glocaltokens.client] Set GLocalAuthenticationTokens client access_token, homegraph, access_token_date and homegraph_date to None
2022-05-25 20:50:56 DEBUG (MainThread) [glocaltokens.client] Set GLocalAuthenticationTokens client username to "t******************", password to "v***************", master_token to "" and android_id to 
2022-05-25 20:50:56 DEBUG (SyncWorker_2) [glocaltokens.client] There is no stored master_token, logging in using username and password
2022-05-25 20:50:56 DEBUG (SyncWorker_2) [glocaltokens.client] There is no stored android_id, generating a new one
2022-05-25 20:50:56 DEBUG (SyncWorker_2) [glocaltokens.client] Generating android id...
2022-05-25 20:50:56 DEBUG (SyncWorker_2) [glocaltokens.client] Generated android id: 6ee92259b8d78d3a
2022-05-25 20:50:56 ERROR (SyncWorker_2) [glocaltokens.client] [!] Could not get master token.
2022-05-25 20:50:56 DEBUG (SyncWorker_2) [glocaltokens.client] Request response: {'Error': 'NeedsBrowser', 'Url': 'https://accounts.google.com/signin/continue?sarp=1&scc=1&continue=https://accounts.google.com/o/android/auth?<REDACTED AUTH DATA HERE>', 'ErrorDetail': 'To access your account, you must sign in on the web. Touch Next to start browser sign-in.'}
2022-05-25 20:50:56 ERROR (MainThread) [custom_components.google_home] ```

**Comment by zhangtemplar** [comment]
Same issue for me.

**Comment by isntw** [comment]
same issue for me

**Comment by srappan** [comment]
Encountering the same error too.
```
2022-05-26 20:20:41 DEBUG (MainThread) [glocaltokens.client] Initializing new GLocalAuthenticationTokens instance.
2022-05-26 20:20:41 DEBUG (MainThread) [glocaltokens.client] Set GLocalAuthenticationTokens client access_token, homegraph, access_token_date and homegraph_date to None
2022-05-26 20:20:41 DEBUG (MainThread) [glocaltokens.client] Set GLocalAuthenticationTokens client username to "s*****************", password to "f***************", master_token to "" and android_id to 
2022-05-26 20:20:41 DEBUG (SyncWorker_6) [glocaltokens.client] There is no stored master_token, logging in using username and password
2022-05-26 20:20:41 DEBUG (SyncWorker_6) [glocaltokens.client] There is no stored android_id, generating a new one
2022-05-26 20:20:41 DEBUG (SyncWorker_6) [glocaltokens.client] Generating android id...
2022-05-26 20:20:41 DEBUG (SyncWorker_6) [glocaltokens.client] Generated android id: 5eeab5fc8c1833e7
2022-05-26 20:20:41 ERROR (SyncWorker_6) [glocaltokens.client] [!] Could not get master token.
2022-05-26 20:20:41 DEBUG (SyncWorker_6) [glocaltokens.client] Request response: {'Error': 'NeedsBrowser', 'Url': 'https://accounts.google.com/signin/continue?sarp=1&scc=1&continue=https://accounts.google.com/o/android/auth?hl%3Den_us%26xoauth_display_name%3DAndroid%2BLogin%2BService%26source%3DAndroid%2BLogin&plt=AKgnsbvE0GM96jrnM1SjcgApksTCPV-CUMiXpK4qi_yfB9HADNxoUL_s988cjiGdnV54Gh7_aWuxEmYKR8z74bL6RYPQCZje5-Zyow-48LgIzsqReG8rndiuHOHjXZ-qy6uK3Ik1_iHj', 'ErrorDetail': 'To access your account, you must sign in on the web. Touch Next to start browser sign-in.'}
2022-05-26 20:20:41 ERROR (MainThread) [custom_components.google_home] 
```

**Comment by kyemacdonald** [comment]
Same as the others - requiring web browser to sign in.

**Comment by Pronown** [comment]
I believe I am experiencing the same issue. I enabled the logger as instructed in the old issue. I wanted to try to help and tried to login to the url it provided in the log... unfortunately it just says "Please Wait". Hope this helps. Let me know if there is anything I should check or try. I don't have any of the integrations mentioned on the old issue.

Stupid Idea, what if I disable 2FA, login, then re-enable 2FA?

```

2022-05-26` 20:14:44 DEBUG (MainThread) [glocaltokens.client] Initializing new GLocalAuthenticationTokens instance.
2022-05-26 20:14:44 DEBUG (MainThread) [glocaltokens.client] Set GLocalAuthenticationTokens client access_token, homegraph, access_token_date and homegraph_date to None
2022-05-26 20:14:44 DEBUG (MainThread) [glocaltokens.client] Set GLocalAuthenticationTokens client username to "p***********************", password to "h***************", master_token to "" and android_id to 
2022-05-26 20:14:44 DEBUG (SyncWorker_1) [glocaltokens.client] There is no stored master_token, logging in using username and password
2022-05-26 20:14:44 DEBUG (SyncWorker_1) [glocaltokens.client] There is no stored android_id, generating a new one
2022-05-26 20:14:44 DEBUG (SyncWorker_1) [glocaltokens.client] Generating android id...
2022-05-26 20:14:44 DEBUG (SyncWorker_1) [glocaltokens.client] Generated android id: (redacted. not sure if its safe to post)
2022-05-26 20:14:44 ERROR (SyncWorker_1) [glocaltokens.client] [!] Could not get master token.
2022-05-26 20:14:44 DEBUG (SyncWorker_1) [glocaltokens.client] Request response: {'Error': 'NeedsBrowser', 'Url': 'https://accounts.google.com/signin/continue?sarp=1&scc=1&continue=https://accounts.google.com/o/android/auth?hl%3Den_us%26xoauth_display_name%3DAndroid%2BLogin%2BService%26source%3DAndroid%2BLogin&plt=AKgnsbu06JAWhr6aDij7t_GrWQE1-SitLChjf5e995mXrG8Dhvh8VsJ6bzgt6zpFCp33R9G3eq1OfGjP_7wOU8QEayYSIcCxJFqozRTJSTmTWha_CRwRj9j7gj85QBJUCbIZNusgBJuX', 'ErrorDetail': 'To access your account, you must sign in on the web. Touch Next to start browser sign-in.'}
2022-05-26 20:14:44 ERROR (MainThread) [custom_components.google_home] 
```

**Comment by DirkTas67** [comment]
I'm having also this problem, HA is installed on Truenas Scale as Truecharts app.

**Comment by ArnyminerZ** [comment]
@Pronown yeah, I believe this is the issue. This was working before, so something has changed on Google's side of authentication. Right now I'm totally out of time, but I will try on a fix for this ASAP.

**Comment by Pronown** [comment]
Hey, no rush, I just figured I'd offer any info I found. Extremely excited to expose these entities to my system. More sensors means more automations for me to dream up.

I tried forcing the "browser" integration to load the url provided in the logs, to see if that would do it, apparently I can't get browser to run at all, nothing happened when I used their direct example to get to Google. - I'm guessing that's because the host machine is RPi 3B+ and I'm pretty sure unless I launch into the UI for the Debian package I'm running, it doesn't actually have a browser? I could be on the wrong track.

As for something I can think of that may be causing 2FA Issues, I know I'm using Google Authenticator as well as a Bluetooth key. It may be freaked out that I have like 14 steps to log in..

**Comment by Pronown** [comment]
@DirkTas67 
What is the difference in TrueNAS and Home Assistant? From what I just researched it's incomplete, but looks exactly like HA? There were a bunch of abbreviations I didn't understand though, so I'm kinda curious what this software does?

**Comment by DirkTas67** [comment]
@Pronown HomeAssistant is an app on the Truenas scale system, truenas scale is like a complete OS for NAS and has also apps, apps like Homeassistant, ESPHome, NodeRed, Mosquitto, Zigbee2mqtt..... and many many more

**Comment by leikoilja** [comment]
**Update:**
Just as mentioned above - google has changed some stuff around authentication logic that breaks this package.

The work is going on around in the underlying package `gpsoauth` that we use in `glocaltokens`:
https://github.com/simon-weber/gpsoauth/issues/37#issuecomment-1140959576

We should spend all attention to fix it in `gpsoauth` first and once it's merged and deployed - we look how we need to alter `glocaltoken` to make it work standalone as well as in `ha-google-home` package :)

**Comment by ArnyminerZ** [comment]
Just for reference, the issue has been adressed at simon-weber/gpsoauth#42, now we only have to wait until a new release is published, [@simon-weber](https://github.com/simon-weber) says it gonna be quick, so let's hope 🤞🏼

**Comment by hugalafutro** [comment]
I just updated to 1.9.11, restarted HA, created new app password for my gmail address, tried to log in with it into integration and still get `[!] Could not get master token.`. Is there something more I need to do? Thanks!

**Comment by DirkTas67** [comment]
Thank you for the update; just installed the new version, restarted Homeassistant, installed the integration and added my gmail and app password and it works! Great!

**Comment by hugalafutro** [comment]
@DirkTas67 Hi, did you have the integration uninstalled and then installed 1.9.11 or did you update? I'm trying to find a difference in the process as 1.9.11 still doesn't work for me (and presumably whoever upvoted my post @ [#528](https://github.com/leikoilja/ha-google-home/issues/528#issuecomment-1143237249))

**Comment by srappan** [comment]
```
2022-06-01 09:59:32 DEBUG (MainThread) [glocaltokens.client] Initializing new GLocalAuthenticationTokens instance.
2022-06-01 09:59:32 DEBUG (MainThread) [glocaltokens.client] Set GLocalAuthenticationTokens client access_token, homegraph, access_token_date and homegraph_date to None
2022-06-01 09:59:32 DEBUG (MainThread) [glocaltokens.client] Set GLocalAuthenticationTokens client username to "s*****************", password to "b***************", master_token to "" and android_id to 
2022-06-01 09:59:32 DEBUG (SyncWorker_5) [glocaltokens.client] There is no stored master_token, logging in using username and password
2022-06-01 09:59:32 DEBUG (SyncWorker_5) [glocaltokens.client] There is no stored android_id, generating a new one
2022-06-01 09:59:32 DEBUG (SyncWorker_5) [glocaltokens.client] Generating android id...
2022-06-01 09:59:32 DEBUG (SyncWorker_5) [glocaltokens.client] Generated android id: 269ef5bf05c1882e
2022-06-01 09:59:32 ERROR (SyncWorker_5) [glocaltokens.client] [!] Could not get master token.
2022-06-01 09:59:32 DEBUG (SyncWorker_5) [glocaltokens.client] Request response: {'Error': 'NeedsBrowser', 'Url': 'https://accounts.google.com/signin/continue?sarp=1&scc=1&continue=https://accounts.google.com/o/android/auth?hl%3Den_us%26xoauth_display_name%3DAndroid%2BLogin%2BService%26source%3DAndroid%2BLogin&plt=AKgnsbt5TfW_ByZba1pdiUbwOThU9q-n_n7s5iwCI2ad28Ja2hhxUdWg6zaOnh1dt-8pnZvF7Yi29AuDMG9k-K-iIaXrLcsBRHA3CfmvvQ0mywajR_CXW5WSBeW_uthzpgYqsYvTOIJJ', 'ErrorDetail': 'To access your account, you must sign in on the web. Touch Next to start browser sign-in.'}
2022-06-01 09:59:32 ERROR (MainThread) [custom_components.google_home] 
```

Same error with 1.9.11

**Comment by dineshkathir** [comment]
`Logger: glocaltokens.client
Source: /usr/local/lib/python3.9/site-packages/glocaltokens/client.py:224
First occurred: 14:41:44 (3 occurrences)
Last logged: 14:44:54

[!] Could not get master token.`

Still the same error. Unable to log in.
I updated to the new version 1.9.11 and tried to reinstall the integration also.
I have tried both Desktop web and Android applications. 

But still facing the same error.

**Comment by DirkTas67** [comment]
@srappan Yes, at the desktop browser

**Comment by DirkTas67** [comment]
@hugalafutro No I just updated the integration

**Comment by bjarnekrottje** [comment]
For me too the same error:
```python
2022-06-01 11:37:38 DEBUG (MainThread) [glocaltokens.client] Initializing new GLocalAuthenticationTokens instance.
2022-06-01 11:37:38 DEBUG (MainThread) [glocaltokens.client] Set GLocalAuthenticationTokens client access_token, homegraph, access_token_date and homegraph_date to None
2022-06-01 11:37:38 DEBUG (MainThread) [glocaltokens.client] Set GLocalAuthenticationTokens client username to "b************", password to "b***************", master_token to "" and android_id to
2022-06-01 11:37:38 DEBUG (SyncWorker_0) [glocaltokens.client] There is no stored master_token, logging in using username and password
2022-06-01 11:37:38 DEBUG (SyncWorker_0) [glocaltokens.client] There is no stored android_id, generating a new one
2022-06-01 11:37:38 DEBUG (SyncWorker_0) [glocaltokens.client] Generating android id...
2022-06-01 11:37:38 DEBUG (SyncWorker_0) [glocaltokens.client] Generated android id: 8a18675a7afa6051
2022-06-01 11:37:38 ERROR (SyncWorker_0) [glocaltokens.client] [!] Could not get master token.
2022-06-01 11:37:38 DEBUG (SyncWorker_0) [glocaltokens.client] Request response: {'Error': 'NeedsBrowser', 'Url': 'https://accounts.google.com/signin/continue?sarp=1&scc=1&continue=https://accounts.google.com/o/android/auth?hl%3Den_us%26xoauth_display_name%3DAndroid%2BLogin%2BService%26source%3DAndroid%2BLogin&plt=AKgnsbvEqZQYwofgrVil4Um2VtvO9qQcVWo1Njgc8VNvpILtIUuerp_udRNBDI25Owldd56rFtLx9HjT_Ej7GjDLCKE8ggxnfiFq7vWDNff4yIHC1ESnc7WkfI8qddfvxUd-us7XtGV-', 'ErrorDetail': 'To access your account, you must sign in on the web. Touch Next to start browser sign-in.'}
2022-06-01 11:37:38 ERROR (MainThread) [custom_components.google_home]
```
Both on desktop (Windows 11) and in the mobile app (Android 12).

**Comment by Pronown** [comment]
Installed with updated with HACS via mobile- No go.
Uninstalled. 
Reinstalled manually with file from here via destop - No go

2FA set:
Security Key
Email
Google Authenticator
Tap On Phone

**Comment by leikoilja** [comment]
Opsies, sorry, gents... 
Let's move back to `ha-google-home` issue thread [here](https://github.com/leikoilja/ha-google-home/issues/528), since `glocaltokens` is fixed and python SDK works just fine. Tested both yesterday and today using provided python `get_tokens` example and works just fine :)

**Comment by KaijuKira86** [comment]
cant log in i have the most current version of everything and its a fresh install of google home integration.

`2022-08-13 18:13:12.964 ERROR (SyncWorker_3) [glocaltokens.client] [!] Could not get master token.
2022-08-13 18:13:12.974 ERROR (MainThread) [custom_components.google_home]
2022-08-13 18:13:34.122 ERROR (SyncWorker_4) [glocaltokens.client] [!] Could not get master token.
2022-08-13 18:13:34.126 ERROR (MainThread) [custom_components.google_home]
2022-08-13 18:14:05.850 ERROR (SyncWorker_0) [glocaltokens.client] [!] Could not get master token.
2022-08-13 18:14:05.856 ERROR (MainThread) [custom_components.google_home]`

**Comment by leikoilja** [comment]
@KaijuKira86, since this issue got marked solved, please open a new issue and provide more details for us to be able to look into it
