### ISSUE TITLE
error trying to get master token

### ISSUE THREAD

**Issue by ndelahun** [leikoilja/glocaltokens#391]
**Describe the bug**
trying to get master token .
When running the example on the first page
from glocaltokens.client import GLocalAuthenticationTokens

```
# Using google username and password first, and only once
client = GLocalAuthenticationTokens(
  username="usrname",
  password="app password"
)

# Get master token
master_token = client.get_master_token()
print("[*] Master token", master_token)
```

 getting error

```
Traceback (most recent call last):
  File "/config/get_token.py", line 10, in <module>
    master_token = client.get_master_token()
  File "/usr/lib/python3.10/site-packages/glocaltokens/client.py", line 230, in get_master_token
    res = perform_master_login(
  File "/usr/lib/python3.10/site-packages/gpsoauth/__init__.py", line 143, in perform_master_login
    return _perform_auth_request(data, proxy)
  File "/usr/lib/python3.10/site-packages/gpsoauth/__init__.py", line 78, in _perform_auth_request
    session.mount(AUTH_URL, AuthHTTPAdapter())
  File "/usr/lib/python3.10/site-packages/requests/adapters.py", line 155, in __init__
    self.init_poolmanager(pool_connections, pool_maxsize, block=pool_block)
  File "/usr/lib/python3.10/site-packages/gpsoauth/__init__.py", line 68, in init_poolmanager
    context.set_ciphers(ssl_.DEFAULT_CIPHERS)
AttributeError: module 'urllib3.util.ssl_' has no attribute 'DEFAULT_CIPHERS'
```

**Comment by leikoilja** [comment]
what's your urllib3 and openssl versions? check https://github.com/leikoilja/glocaltokens/issues/332

**Comment by ndelahun** [comment]
urllib3 is version 2.0.3 
open ssl version 3.0.9

**Comment by ChalyFlavour** [comment]
Sorry for duplicated post, but maybe this is of help.
I solved this here: https://github.com/leikoilja/glocaltokens/issues/332#issuecomment-1633787921
