### ISSUE TITLE
`Castlistner` should implement `remove_service`

### ISSUE THREAD

**Issue by DurgNomis-drol** [leikoilja/glocaltokens#46]
**Describe the bug**

```text
2021-03-21 10:56:13 ERROR (zeroconf-ServiceBrowser__googlecast._tcp.local._264) [root] Uncaught thread exception
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/usr/local/lib/python3.8/site-packages/zeroconf/__init__.py", line 1760, in run
    self._service_state_changed.fire(
  File "/usr/local/lib/python3.8/site-packages/zeroconf/__init__.py", line 1513, in fire
    h(**kwargs)
  File "/usr/local/lib/python3.8/site-packages/zeroconf/__init__.py", line 1618, in on_change
    listener.remove_service(*args)
AttributeError: 'CastListener' object has no attribute 'remove_service'
```

See this link [Homeassistant/core#48117](https://github.com/home-assistant/core/issues/48117)

**To Reproduce**

Appears first time i restart, but only once.

**Expected behavior**

No error message.

**Screenshots**

**Additional context**

**Comment by leikoilja** [comment]
Really good find, thank you, @DurgNomis-drol 💥

**Comment by KapJI** [comment]
I'd say it's more a bugfix rather that feature :)

**Comment by leikoilja** [comment]
Uuu, you are right, @KapJI, thanks :)
